# Welcome to Jekyll Paper for Github
#
# This is the configuration file for your blog, please change these items after forked.

title: Ivan Ivanchuck | Blog
email: l3r8y@duck.com
name: Ivan Ivanchuck
description: >- # this means to ignore newlines until "baseurl:"
  Here my small blog about sowftware.
keywords: [programming, java, ruby, oop, open-source]
baseurl: '' # the subpath of your site, e.g. /`blog
url: 'https://www.l3r8y.ru' # the base hostname & protocol for your site, e.g. http://example.com
domain: 'www.l3r8y.ru' # the domain name for your site, e.g. example.com
language: en

analytics: G-XTETTK84JF

comments: true
disqus: l3r8y-blog

mathjax: true # Math support
diagram: true # Diagrams support

paginate: 25
paginate_path: '/page:num/'

permalink: /:year/:month/:day/:title

sass:
  sass_dir: _sass
  style: expanded # compressed, compact, expanded or compressed

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-admin

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
