---
name: jekyll
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
concurrency:
  group: jekyll-${{ github.ref }}
  cancel-in-progress: true
jobs:
  jekyll:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: l3r8yJ/l3r8yj.github.io@master